### ISSUE TITLE
The plugin cannot be loaded

### ISSUE THREAD

**Issue by vtortola** [baseclass/Contrib.SpecFlow.Selenium.NUnit#3]
Hi,

As soon as I installed the library through NuGet I cannot run tests anymore because this error:

```
AngularJS.SpecFlow.Registration.RegistrationPageFeatureExampleFeature   (TestFixtureSetUp):
SetUp : TechTalk.SpecFlow.SpecFlowException : Unable to load plugin: Baseclass.Contrib.SpecFlow.Selenium.NUnit. Please check http://go.specflow.org/doc-plugins for details.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'Baseclass.Contrib.SpecFlow.Selenium.NUnit.SpecFlowPlugin' or one of its dependencies. The system cannot find the file specified.
```

I installed the plugin through NuGet. I am using:
- Visual Studio 2010
- .NET 4.0
- WebDriver 2.41.0.0
- SpecFlow 1.9.0.77
- nUnit 2.6.0.12051

They are basically the latest versions available in NuGet. I am using the default config. I can disable the plugin and then it works as before.

What maybe the problem?

The full exception is:

```
at TechTalk.SpecFlow.Infrastructure.RuntimePluginLoader.LoadPlugin(PluginDescriptor pluginDescriptor)
at TechTalk.SpecFlow.Infrastructure.TestRunContainerBuilder.<>c__DisplayClass3.<LoadPlugins>b__1(PluginDescriptor pd)
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Linq.Enumerable.<ConcatIterator>d__71`1.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at TechTalk.SpecFlow.Infrastructure.TestRunContainerBuilder.CreateContainer(IRuntimeConfigurationProvider configurationProvider)
at TechTalk.SpecFlow.TestRunnerManager.CreateTestRunner(TestRunnerKey key)
at TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(TestRunnerKey key)
at AngularJS.SpecFlow.Registration.RegistrationPageFeatureExampleFeature.FeatureSetup() in C:\Code\AngularJSPrototype\Prototype\AngularJS.SpecFlow\AngularJS.SpecFlow\Registration\Registration.feature.cs:line 0
--FileNotFoundException
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
at System.Reflection.Assembly.Load(String assemblyString)
at TechTalk.SpecFlow.Infrastructure.RuntimePluginLoader.LoadPlugin(PluginDescriptor pluginDescriptor)
```

Thanks.

**Comment by romerod** [comment]
Did you check the file path which was added to the configuration file?

---

Von: vtortola notifications@github.com
Gesendet: Mittwoch, 21. Mai 2014 11:38
An: baseclass/Contrib.SpecFlow.Selenium.NUnit
Betreff: [Contrib.SpecFlow.Selenium.NUnit] The plugin cannot be loaded (#3)

Hi,

As soon as I installed the library through NuGet I cannot run tests anymore because this error:

AngularJS.SpecFlow.Registration.RegistrationPageFeatureExampleFeature   (TestFixtureSetUp):
SetUp : TechTalk.SpecFlow.SpecFlowException : Unable to load plugin: Baseclass.Contrib.SpecFlow.Selenium.NUnit. Please check http://go.specflow.org/doc-plugins for details.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'Baseclass.Contrib.SpecFlow.Selenium.NUnit.SpecFlowPlugin' or one of its dependencies. The system cannot find the file specified.

I installed the plugin through NuGet. I am using:
-   Visual Studio 2010
-   .NET 4.0
-   WebDriver 2.41.0.0
-   SpecFlow 1.9.0.77
-   nUnit 2.6.0.12051

They are basically the latest versions available in NuGet. I am using the default config. I can disable the plugin and then it works as before.

What maybe the problem?

Thanks.

##

**Comment by vtortola** [comment]
Yes. The path exists.

I can see a warning in Visual Studio:

```
Warning 36  The primary reference "Baseclass.Contrib.SpecFlow.Selenium.NUnit.SpecFlowPlugin" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".    AngularJS.SpecFlow
```

May it be related?

**Comment by romerod** [comment]
Your project is built with 4.0? There is currently no 4.0 build, can't you switch?

**Comment by vtortola** [comment]
Argh.. no :( Visual Studio 2010 does not support 4.5 . It is odd because NuGet didn't prevent me from installing the package in 4.0. There are plans to switch to VS2012, but not at the moment. 

Is there anything preventing me from build the project from the source myself in .NET 4.0 ?

Cheers.

**Comment by romerod** [comment]
You can add an additional project which builds the linked source files in 4.0 contribute that to github and i'll take care of creating a new nuget packet version

**Comment by vtortola** [comment]
Hi,
I pulled three files that build the solution in .NET 4.0.

I have now another issue that I am not completely sure it is related with this, so I will detail it in another  post.

Cheers.
