### ISSUE TITLE
NullReferenceException when running tests

### ISSUE THREAD

**Issue by vtortola** [baseclass/Contrib.SpecFlow.Selenium.NUnit#5]
Hi,

Everytime I try to run a test, I get a null reference exception:

```
TestApplication.UiTests.CalculatorFeatureFeature.AddTwoNumbers:
System.NullReferenceException : Object reference not set to an instance of an object.
```

This is happening even in the examples provided in GitHub. 
What I did:
- downloaded the code from GitHub
- opened the solution TestApplication.sln.
- built it
- opened the nUnit runner
- opened the TestApplication.UiTests.dll library
- run the tests
- then I get:

```
TestApplication.UiTests.CalculatorFeatureFeature.AddTwoNumbers:
System.NullReferenceException : Object reference not set to an instance of an object.
TestApplication.UiTests.CalculatorFeatureFeature.AddTwoNumbers:
System.NullReferenceException : Object reference not set to an instance of an object.
TestApplication.UiTests.CalculatorFeatureFeature.AddTwoNumbers:
System.NullReferenceException : Object reference not set to an instance of an object.
TestApplication.UiTests.CalculatorFeatureFeature.AddTwoNumbers:
System.NullReferenceException : Object reference not set to an instance of an object.
TestApplication.UiTests.CalculatorFeatureFeature.BasepageIsCalculator:
System.NullReferenceException : Object reference not set to an instance of an object.
TestApplication.UiTests.CalculatorFeatureFeature.BasepageIsCalculator:
System.NullReferenceException : Object reference not set to an instance of an object.
TestApplication.UiTests.CalculatorFeatureFeature.BasepageIsCalculator:
System.NullReferenceException : Object reference not set to an instance of an object.
```

The exception details shows:

```
at NUnit.Core.Extensibility.ParameterSet.FromDataSource(Object source)
at NUnit.Core.Builders.TestCaseParameterProvider.GetTestCasesFor(MethodInfo method)
```

I am using:
- VS 2013 Express
- . NET 4.5
- WebDriver 2.35.0.0
- SpecFlow 1.9.0.77

I have tried in .NET 4.0 and Visual Studio 2010 with libraries compiled for that version, and got the same issue. 

Any idea what could be the problem?

**Comment by romerod** [comment]
What version of nunit are you using?

**Comment by vtortola** [comment]
Right on the spot. Apparently there is two nUnit versions installed, one for 2.0 and other for the rest. 

I works great, nice job.
